<?php
session_start();
$sesnama = $_POST["txtNama"];
$sesemail = $_POST["txtEmail"];
$sespesan = $_POST["txtPesan"];
$sesNIM = $_POST["txtNIM"];
$sesNamaLengkap = $_POST["txtNamaLengkap"];
$sesTempatLahir = $_POST["txtTempatLahir"];
$sesTanggalLahir = $_POST["txtTanggalLahir"];
$sesHobi = $_POST["txtHobi"];
$sesPasangan = $_POST["txtPasangan"];
$sesPekerjaan = $_POST["txtPekerjaan"];
$sesNamaOrangTua = $_POST["txtNamaOrangTua"];
$sesNamaKakak = $_POST["txtNamakakak"];
$sesNamaAdik = $_POST["txtNamaAdik"];
$_SESSION["sesnama"] = $sesnama;
$_SESSION["sesemail"] = $sesemail;
$_SESSION["sespesan"] = $sespesan;
$_SESSION["sesNIM"] = $sesNIM;
$_SESSION["sesNamaLengkap"] = $sesNamaLengkap;
$_SESSION["sesTempatLahir"] = $sesTempatLahir;
$_SESSION["sesTanggalLahir"] = $sesTanggalLahir;
$_SESSION["sesHobi"] = $sesHobi;
$_SESSION["sesPasangan"] = $sesPasangan;
$_SESSION["sesPekerjaan"] = $sesPekerjaan;
$_SESSION["sesNamaOrangTua"] = $sesNamaOrangTua;
$_SESSION["sesNamaKakak"] = $sesNamaKakak;
$_SESSION["sesNamaAdik"] = $sesNamAadik;
header("location: index.php");
?>